* Encoding: windows-1252.
** scale=12 (EORTC C30: loss of appetite).
USE ALL. 
COMPUTE filter_$=(scale=12).
FILTER BY filter_$.
EXECUTE.
SORT CASES BY treatment_dich.
SPLIT FILE LAYERED BY treatment_dich.
MIXED outcome BY metingR groep
  /CRITERIA=DFMETHOD(SATTERTHWAITE) CIN(95) MXITER(100) MXSTEP(10) SCORING(1) SINGULAR(0.000000000001) HCONVERGE(0, ABSOLUTE) LCONVERGE(0, ABSOLUTE) PCONVERGE(0.000001, ABSOLUTE)    
  /FIXED=metingR groep metingR*groep | SSTYPE(3) /METHOD=ML /PRINT=SOLUTION /RANDOM=INTERCEPT | SUBJECT(pident) COVTYPE(CS) /EMMEANS=TABLES(metingR*groep) .
SORT CASES BY treatment_dich measurement groep.
SPLIT FILE LAYERED BY treatment_dich measurement groep.
FREQUENCIES VARIABLES=outcome /FORMAT=NOTABLE /STATISTICS=STDDEV MEAN /ORDER=ANALYSIS.
SPLIT FILE OFF.

** scale=15 (EORTC C30: financial problems).
USE ALL. 
COMPUTE filter_$=(scale=15).
FILTER BY filter_$.
EXECUTE.
SORT CASES BY statusM24.
SPLIT FILE LAYERED BY statusM24.
MIXED outcome BY metingR groep
  /CRITERIA=DFMETHOD(SATTERTHWAITE) CIN(95) MXITER(100) MXSTEP(10) SCORING(1) SINGULAR(0.000000000001) HCONVERGE(0, ABSOLUTE) LCONVERGE(0, ABSOLUTE) PCONVERGE(0.000001, ABSOLUTE)    
  /FIXED=metingR groep metingR*groep | SSTYPE(3) /METHOD=ML /PRINT=SOLUTION /RANDOM=INTERCEPT | SUBJECT(pident) COVTYPE(CS) /EMMEANS=TABLES(metingR*groep) .
SORT CASES BY statusM24 measurement groep.
SPLIT FILE LAYERED BY statusM24 measurement groep.
FREQUENCIES VARIABLES=outcome /FORMAT=NOTABLE /STATISTICS=STDDEV MEAN /ORDER=ANALYSIS.
SPLIT FILE OFF.

** scale=31 (EORTC HN35: swallowing).
USE ALL. 
COMPUTE filter_$=(scale=31).
FILTER BY filter_$.
EXECUTE.
SORT CASES BY comorb_3cat.
SPLIT FILE LAYERED BY comorb_3cat.
MIXED outcome BY metingR groep
  /CRITERIA=DFMETHOD(SATTERTHWAITE) CIN(95) MXITER(100) MXSTEP(10) SCORING(1) SINGULAR(0.000000000001) HCONVERGE(0, ABSOLUTE) LCONVERGE(0, ABSOLUTE) PCONVERGE(0.000001, ABSOLUTE)    
  /FIXED=metingR groep metingR*groep | SSTYPE(3) /METHOD=ML /PRINT=SOLUTION /RANDOM=INTERCEPT | SUBJECT(pident) COVTYPE(CS) /EMMEANS=TABLES(metingR*groep) .
SORT CASES BY comorb_3cat measurement groep.
SPLIT FILE LAYERED BY comorb_3cat measurement groep.
FREQUENCIES VARIABLES=outcome /FORMAT=NOTABLE /STATISTICS=STDDEV MEAN /ORDER=ANALYSIS.
SPLIT FILE OFF.

** scale=24 (CWS fear of recurrence).
USE ALL. 
COMPUTE filter_$=(scale=24).
FILTER BY filter_$.
EXECUTE.
SORT CASES BY cidep11.24.
SPLIT FILE LAYERED BY cidep11.24.
MIXED outcome BY metingR groep
  /CRITERIA=DFMETHOD(SATTERTHWAITE) CIN(95) MXITER(100) MXSTEP(10) SCORING(1) SINGULAR(0.000000000001) HCONVERGE(0, ABSOLUTE) LCONVERGE(0, ABSOLUTE) PCONVERGE(0.000001, ABSOLUTE)    
  /FIXED=metingR groep metingR*groep | SSTYPE(3) /METHOD=ML /PRINT=SOLUTION /RANDOM=INTERCEPT | SUBJECT(pident) COVTYPE(CS) /EMMEANS=TABLES(metingR*groep) .
SORT CASES BY scale measurement groep.
SPLIT FILE LAYERED BY scale measurement groep.
FREQUENCIES VARIABLES=outcome /FORMAT=NOTABLE /STATISTICS=STDDEV MEAN /ORDER=ANALYSIS.
SPLIT FILE OFF.

** scale=20 (dJG: emotional loneliness).
USE ALL. 
COMPUTE filter_$=(scale=20).
FILTER BY filter_$.
EXECUTE.
SORT CASES BY Nklb_bmi.
SPLIT FILE LAYERED BY Nklb_bmi.
MIXED outcome BY metingR groep
  /CRITERIA=DFMETHOD(SATTERTHWAITE) CIN(95) MXITER(100) MXSTEP(10) SCORING(1) SINGULAR(0.000000000001) HCONVERGE(0, ABSOLUTE) LCONVERGE(0, ABSOLUTE) PCONVERGE(0.000001, ABSOLUTE)    
  /FIXED=metingR groep metingR*groep | SSTYPE(3) /METHOD=ML /PRINT=SOLUTION /RANDOM=INTERCEPT | SUBJECT(pident) COVTYPE(CS) /EMMEANS=TABLES(metingR*groep) .
SORT CASES BY Nklb_bmi measurement groep.
SPLIT FILE LAYERED BY Nklb_bmi measurement groep.
FREQUENCIES VARIABLES=outcome /FORMAT=NOTABLE /STATISTICS=STDDEV MEAN /ORDER=ANALYSIS.
SPLIT FILE OFF.

** scale=43 (EORTC HN35: painkillers).
USE ALL. 
COMPUTE filter_$=(scale=43).
FILTER BY filter_$.
EXECUTE.
SORT CASES BY fam04a_cat.
SPLIT FILE LAYERED BY fam04a_cat.
GENLIN outcome_dich (REFERENCE=LAST) BY Measurement groep (ORDER=ASCENDING)
  /MODEL Measurement groep Measurement*groep INTERCEPT=YES DISTRIBUTION=BINOMIAL LINK=LOGIT
  /CRITERIA METHOD=FISHER(1) SCALE=1 MAXITERATIONS=100 MAXSTEPHALVING=5 PCONVERGE=1E-006(ABSOLUTE) SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /REPEATED SUBJECT=pident SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST MAXITERATIONS=100 PCONVERGE=1e-006(ABSOLUTE) UPDATECORR=1
  /MISSING CLASSMISSING=EXCLUDE /PRINT CPS DESCRIPTIVES MODELINFO FIT SUMMARY SOLUTION (EXPONENTIATED).
CROSSTABS /TABLES=outcome_dich BY groep BY Measurement /FORMAT=AVALUE TABLES /CELLS=COUNT COLUMN  /COUNT ROUND CELL.
SORT CASES BY fam04a_cat measurement groep.
SPLIT FILE LAYERED BY fam04a_cat measurement groep.
FREQUENCIES VARIABLES=outcome /ORDER=ANALYSIS.
SPLIT FILE OFF.

** scale=29 (PASE - total score (categorical)).
USE ALL. 
COMPUTE filter_$=(scale=29).
FILTER BY filter_$.
EXECUTE.
SORT CASES BY gender.
SPLIT FILE LAYERED BY gender.
GENLIN outcome (ORDER=ASCENDING) BY Measurement groep (ORDER=ASCENDING) 
  /MODEL Measurement groep Measurement*groep INTERCEPT=YES DISTRIBUTION=MULTINOMIAL LINK=CUMLOGIT
  /CRITERIA METHOD=FISHER(1) SCALE=1 MAXITERATIONS=100 MAXSTEPHALVING=5 PCONVERGE=1E-006(ABSOLUTE) SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /REPEATED SUBJECT=pident SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST MAXITERATIONS=100 PCONVERGE=1e-006(ABSOLUTE) UPDATECORR=1
  /MISSING CLASSMISSING=EXCLUDE /PRINT CPS DESCRIPTIVES MODELINFO FIT SUMMARY SOLUTION (EXPONENTIATED).
CROSSTABS /TABLES=outcome BY groep BY Measurement /FORMAT=AVALUE TABLES /CELLS=COUNT COLUMN  /COUNT ROUND CELL.
SORT CASES BY gender measurement groep.
SPLIT FILE LAYERED BY gender measurement groep.
FREQUENCIES VARIABLES=outcome /ORDER=ANALYSIS.
SPLIT FILE OFF.
