* Encoding: UTF-8.
** multivariable voor scale=44 (dichotome PRO).
USE ALL. 
COMPUTE filter_$=(scale=44).
FILTER BY filter_$.
EXECUTE.
CROSSTABS /TABLES=comorbidity BY groep BY Measurement /FORMAT=AVALUE TABLES /CELLS=COUNT /COUNT ROUND CELL.
GENLIN outcome_dich (REFERENCE=LAST) BY Measurement groep comorb_3cat (ORDER=ASCENDING)
  /MODEL Measurement groep Measurement*groep comorb_3cat groep*comorb_3cat Measurement*comorb_3cat Measurement*groep*comorb_3cat INTERCEPT=YES DISTRIBUTION=BINOMIAL LINK=LOGIT
  /CRITERIA METHOD=FISHER(1) SCALE=1 MAXITERATIONS=100 MAXSTEPHALVING=5 PCONVERGE=1E-006(ABSOLUTE) SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /REPEATED SUBJECT=pident SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST MAXITERATIONS=100 PCONVERGE=1e-006(ABSOLUTE) UPDATECORR=1
  /MISSING CLASSMISSING=EXCLUDE /PRINT CPS DESCRIPTIVES MODELINFO FIT SUMMARY SOLUTION (EXPONENTIATED).
* dan geen effect modificator meer.

