* Encoding: windows-1252.
** Table 2.
SORT CASES BY scale .
SPLIT FILE LAYERED BY scale .

USE ALL.
COMPUTE filter_$=(type=2).
VARIABLE LABELS filter_$ 'FILTER'.
VALUE LABELS filter_$ 0 'Not Selected' 1 'Selected'.
FORMATS filter_$ (f1.0).
FILTER BY filter_$.
EXECUTE.
MIXED outcome BY metingR groep
  /CRITERIA=DFMETHOD(SATTERTHWAITE) CIN(95) MXITER(100) MXSTEP(10) SCORING(1) SINGULAR(0.000000000001) HCONVERGE(0, ABSOLUTE) LCONVERGE(0, ABSOLUTE) PCONVERGE(0.000001, ABSOLUTE)    
  /FIXED=metingR groep metingR*groep | SSTYPE(3) /METHOD=ML /PRINT=SOLUTION /RANDOM=INTERCEPT | SUBJECT(pident) COVTYPE(CS) /EMMEANS=TABLES(metingR*groep) .

USE ALL.
COMPUTE filter_$=(type=0).
FILTER BY filter_$.
EXECUTE.
GENLIN outcome_dich (REFERENCE=LAST) BY Measurement groep (ORDER=ASCENDING) /MODEL Measurement groep Measurement*groep INTERCEPT=YES DISTRIBUTION=BINOMIAL LINK=LOGIT
  /CRITERIA METHOD=FISHER(1) SCALE=1 MAXITERATIONS=100 MAXSTEPHALVING=5 PCONVERGE=1E-006(ABSOLUTE) SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /REPEATED SUBJECT=pident SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST MAXITERATIONS=100 PCONVERGE=1e-006(ABSOLUTE) UPDATECORR=1
  /MISSING CLASSMISSING=EXCLUDE /PRINT CPS DESCRIPTIVES MODELINFO FIT SUMMARY SOLUTION (EXPONENTIATED).

USE ALL.
COMPUTE filter_$=(type=1).
FILTER BY filter_$.
EXECUTE.
GENLIN outcome (ORDER=ASCENDING) BY Measurement groep (ORDER=ASCENDING) /MODEL Measurement groep Measurement*groep  DISTRIBUTION=MULTINOMIAL LINK=CUMLOGIT
  /CRITERIA METHOD=FISHER(1) SCALE=1 MAXITERATIONS=100 MAXSTEPHALVING=5 PCONVERGE=1E-006(ABSOLUTE) SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /REPEATED SUBJECT=pident SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST MAXITERATIONS=100 PCONVERGE=1e-006(ABSOLUTE) UPDATECORR=1
  /MISSING CLASSMISSING=EXCLUDE /PRINT CPS DESCRIPTIVES MODELINFO FIT SUMMARY SOLUTION (EXPONENTIATED).


** Supplemental Tables 2 and 3.
SORT CASES BY scale measurement groep.
SPLIT FILE LAYERED BY scale measurement groep.
USE ALL.
COMPUTE filter_$=(type=2).
FILTER BY filter_$.
EXECUTE.
FREQUENCIES VARIABLES=outcome /FORMAT=NOTABLE /STATISTICS=STDDEV MEAN /ORDER=ANALYSIS.
USE ALL.
COMPUTE filter_$=(type<2).
FILTER BY filter_$.
EXECUTE.
FREQUENCIES VARIABLES=outcome /ORDER=ANALYSIS.
FILTER OFF.
USE ALL.
EXECUTE.
SPLIT FILE OFF.
